### PR TITLE
updated the logo for X(previously twitter)

### PR DESCRIPTION
**Pull request by Murdock9803**
### Description of Problem
Just above the footer on the main website, The social media logos are present. The logo of X (twitter) is the old one, and needs to be updated.

### Changes
- [x] Deleted the old logo
- [x] Added new logo in `svg` format.

### CODE REVIEW

**Comment by Murdock9803** [comment]
@sebastiangollob @wslany   Please review the PR

**Comment by sebastiangollob** [comment]
Hi, thank you for the contribution. Please also change the URL accordingly. twitter.com -> x.com

**Review by sebastiangollob — CHANGES_REQUESTED** [review]
Also change the name of the logo to `x_logo.svg` to keep consistency

**Comment by Murdock9803** [comment]
@sebastiangollob I updated the URL and changed the name of the SVG file. However, both twitter.com and x.com work fine for any account as of now. I changed the URL to `x.com` and it works fine.

**Review by sebastiangollob — APPROVED** [review]
Thank you!

**Pull request merged**
